/*
 * Wallaby.js - v1.0.279
 * http://wallabyjs.com
 * Copyright (c) 2014-2016 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var tracer=global.$_$tracer,Runner,TestCollection,Test,runner,avaInstalled=!1,errorFormatter,avaExports;try{var Module=require("module").Module,modulePrototype=Module.prototype,originalRequire=modulePrototype.require;modulePrototype.require=function(e){if("ava"===e){var t=runner.test;return t["default"]=t,t}return originalRequire.call(this,e)};var originalObjectDefineProperty=Object.defineProperty;Object.defineProperty=function(e,t,i){return"AssertionError"===t&&(i.writable=!0),originalObjectDefineProperty.apply(this,arguments)},require("ava/lib/assert"),Runner=require("ava/lib/runner"),Object.defineProperty=originalObjectDefineProperty,TestCollection=require("ava/lib/test-collection"),Test=require("ava/lib/test"),errorFormatter=require("ava/lib/enhance-assert").formatter();var originalTestCollectionAdd=TestCollection.prototype.add;TestCollection.prototype.add=function(e){return e.metadata.serial=!0,e.metadata.skipped=e.metadata.skipped||tracer.hasSpecFilter()&&!tracer.specFilter([e.title]),originalTestCollectionAdd.apply(this,arguments)};var originalTestRun=Test.prototype.run;Test.prototype.run=function(){runner.emit("wallaby.test",this);try{return tracer.specSyncStart(),originalTestRun.apply(this,arguments)}finally{tracer.specSyncEnd()}};var originalRunnerAddTestResult=Runner.prototype._addTestResult;Runner.prototype._addTestResult=function(e){var t=originalRunnerAddTestResult.apply(this,arguments);return runner.emit("wallaby.testResult",e),t},avaInstalled=!0}catch(e){tracer.start(function(){tracer.reportGlobalError("ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?")}),module.exports={init:function(){return{configure:function(){}}}}}if(avaInstalled){var testFiles=[];tracer.start(function(){testFiles.forEach(function(e){require(e)});var e=global.$_$session,t=!1,i=function(){return e!==global.$_$session},n=function(){t||i()||(t=!0,tracer.complete())},s=function(e){return"test"!==e.metadata.type},r=tracer.initialSpecId();runner.on("wallaby.test",function(e){i()||s(e)||(e._id=++r,tracer.specStart(e._id,e.title))}),runner.on("wallaby.testResult",function(e){if(!i()){console.log(e);var t=e.passed;e=e.result;var n=s(e);if(!t||!n){var r=tracer.specEnd(),a={id:e._id,timeRange:r,name:e.title,suite:[],success:t,skipped:e.metadata.skipped||e.metadata.todo,time:e.duration,log:[],hook:n?e.metadata.type:void 0};if(!a.success&&!a.skipped){var o=e.assertError;o.powerAssertContext&&(o.message=errorFormatter(o.powerAssertContext)),o.showDiff=!0;var l={message:o.message,stack:o.stack};tracer.setAssertionData(o,l),a.log.push(l)}a.log.length||delete a.log,tracer.result(a)}}}),tracer.started({total:"unknown number of"}),runner.run({}).then(n)}),module.exports={init:function(e){return runner=new Runner,testFiles=e,runner}}}