/*
 * Wallaby.js - v1.0.279
 * http://wallabyjs.com
 * Copyright (c) 2014-2016 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
!function(e){function t(e,t){for(var i in t)e[i]=t[i]}var i=e.$_$tracer;jasmineRequire.ExceptionFormatter=function(){function e(){this.message=function(e){return e?e.name&&e.message?e.name+": "+e.message:e.toString():"empty error"},this.stack=function(e){return e?e.stack:null}}return e},jasmineRequire.SpyStrategy=function(){function e(e){e=e||{};var t=e.name||"unknown",i=e.fn||function(){},n=e.getSpy||function(){},s=function(){};this.identity=function(){return t},this.exec=function(){return s.apply(this,arguments)},this.callThrough=function(){return s=i,n()},this.returnValue=function(e){return s=function(){return e},n()},this.returnValues=function(){var e=Array.prototype.slice.call(arguments);return s=function(){return e.shift()},n()},this.throwError=function(e){return s=function(){throw e instanceof Error?e:new Error(e)},n()},this.callFake=function(e){return s=e,n()},this.stub=function(e){return s=function(){},n()}}return e},e.jasmine=jasmineRequire.core(jasmineRequire),e.wallaby.testFramework=jasmine;var n=jasmine.getEnv(),s=jasmineRequire["interface"](e.jasmine,n);t(e,s);var r=[],a=n.describe;n.describe=function(){r.push(arguments[0]);var e=Function.prototype.apply.call(a,this,arguments);return r.pop(),e};var o=n.fdescribe;n.fdescribe=function(){r.push(arguments[0]);var e=Function.prototype.apply.call(o,this,arguments);return r.pop(),e};var l=n.it;n.it=function(){var e=arguments[1];if("encountered a declaration exception"===arguments[0])return e();if(!e)return Function.prototype.apply.call(l,this,arguments);e.length?arguments[1]=function(t){i.specSyncStart();try{var n=Function.prototype.apply.call(e,this,arguments)}finally{i.specSyncEnd()}return n}:arguments[1]=function(){i.specSyncStart();try{var t=Function.prototype.apply.call(e,this,arguments)}finally{i.specSyncEnd()}return t};var t=Function.prototype.apply.call(l,this,arguments),n=r.slice();return n.push(t.description),t.disabled=i.hasSpecFilter()&&!i.specFilter(n),t};var u=n.afterEach;n.afterEach=function(){if(i.needToNotifySingleTestRun()){var e=arguments[0];e.length?arguments[0]=function(t){i.notifySingleTestAfterEach(function(){e(t)})}:arguments[0]=function(t){i.notifySingleTestAfterEach(function(){try{e()}finally{t()}})}}return Function.prototype.apply.call(u,this,arguments)}}(window);