/*
 * Wallaby.js - v1.0.279
 * http://wallabyjs.com
 * Copyright (c) 2014-2016 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
function NyanCat(e){Base.call(this,e);var t=this,i=(this.stats,.75*Base.window.width|0),n=(this.rainbowColors=t.generateColors(),this.colorIndex=0,this.numberOfLines=4,this.trajectories=[[],[],[],[]],this.nyanCatWidth=11);this.trajectoryWidthMax=i-n,this.scoreboardWidth=5,this.tick=0;e.on("start",function(){Base.cursor.hide(),t.draw()}),e.on("pending",function(e){t.draw()}),e.on("pass",function(e){t.draw()}),e.on("fail",function(e,i){t.draw()}),e.on("end",function(){Base.cursor.show();for(var e=0;e<t.numberOfLines;e++)write("\n");t.epilogue()})}function write(e){process.stdout.write(e)}var Base=require("./base");exports=module.exports=NyanCat,NyanCat.prototype.draw=function(){this.appendRainbow(),this.drawScoreboard(),this.drawRainbow(),this.drawNyanCat(),this.tick=!this.tick},NyanCat.prototype.drawScoreboard=function(){function e(e,t){write(" "),write(Base.color(e,t)),write("\n")}var t=this.stats;e("green",t.passes),e("fail",t.failures),e("pending",t.pending),write("\n"),this.cursorUp(this.numberOfLines)},NyanCat.prototype.appendRainbow=function(){for(var e=this.tick?"_":"-",t=this.rainbowify(e),i=0;i<this.numberOfLines;i++){var n=this.trajectories[i];n.length>=this.trajectoryWidthMax&&n.shift(),n.push(t)}},NyanCat.prototype.drawRainbow=function(){var e=this;this.trajectories.forEach(function(t,i){write("["+e.scoreboardWidth+"C"),write(t.join("")),write("\n")}),this.cursorUp(this.numberOfLines)},NyanCat.prototype.drawNyanCat=function(){var e=this,t=this.scoreboardWidth+this.trajectories[0].length,i="["+t+"C",n="";write(i),write("_,------,"),write("\n"),write(i),n=e.tick?"  ":"   ",write("_|"+n+"/\\_/\\ "),write("\n"),write(i),n=e.tick?"_":"__";var s=e.tick?"~":"^";write(s+"|"+n+this.face()+" "),write("\n"),write(i),n=e.tick?" ":"  ",write(n+'""  "" '),write("\n"),this.cursorUp(this.numberOfLines)},NyanCat.prototype.face=function(){var e=this.stats;return e.failures?"( x .x)":e.pending?"( o .o)":e.passes?"( ^ .^)":"( - .-)"},NyanCat.prototype.cursorUp=function(e){write("["+e+"A")},NyanCat.prototype.cursorDown=function(e){write("["+e+"B")},NyanCat.prototype.generateColors=function(){for(var e=[],t=0;42>t;t++){var i=Math.floor(Math.PI/3),n=t*(1/6),s=Math.floor(3*Math.sin(n)+3),r=Math.floor(3*Math.sin(n+2*i)+3),a=Math.floor(3*Math.sin(n+4*i)+3);e.push(36*s+6*r+a+16)}return e},NyanCat.prototype.rainbowify=function(e){if(!Base.useColors)return e;var t=this.rainbowColors[this.colorIndex%this.rainbowColors.length];return this.colorIndex+=1,"[38;5;"+t+"m"+e+"[0m"},NyanCat.prototype.__proto__=Base.prototype;